# Generated by Django 4.2 on 2026-02-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0009_studentprofile_maintenanceprofile_auditorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('maintenance', '维修人员'), ('auditor', '审核员'), ('admin', '超级管理员')], default='student', max_length=20, verbose_name='身份角色'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_dorm', '待审核员审核'), ('pending_dispatch', '待派单'), ('repairing', '维修中'), ('finished', '维修完成(待评价)'), ('closed', '已结单'), ('rejected', '已驳回')], default='pending_dorm', max_length=20),
        ),
    ]
