# Generated by Django 4.2 on 2026-02-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0012_ticket_is_anonymous_ticket_rejected_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_url',
            field=models.URLField(blank=True, default='', verbose_name='头像地址'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('unknown', '未知'), ('male', '男'), ('female', '女')], default='unknown', max_length=10, verbose_name='性别'),
        ),
    ]
