# Generated by Django 4.2 on 2026-02-23 11:57

from django.db import migrations, models
import tickets_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0013_customuser_avatar_url_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=tickets_api.models._user_avatar_upload_to, verbose_name='头像文件'),
        ),
    ]
