# Generated by Django 4.2 on 2026-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0014_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用 AI 助手')),
                ('api_base_url', models.CharField(blank=True, default='https://api.deepseek.com/v1', max_length=255, verbose_name='API Base URL')),
                ('api_model', models.CharField(blank=True, default='deepseek-chat', max_length=100, verbose_name='模型')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API Key')),
                ('timeout_seconds', models.IntegerField(default=30, verbose_name='超时(秒)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 配置',
                'verbose_name_plural': 'AI 配置',
            },
        ),
    ]
