# Generated by Django 4.2 on 2026-05-17 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tickets_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0016_aichatlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='维修人员姓名')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='所属班组/专业')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='职称/岗位')),
                ('honor', models.CharField(blank=True, max_length=200, verbose_name='荣誉称号')),
                ('description', models.TextField(blank=True, verbose_name='服务事迹')),
                ('score', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='服务评分')),
                ('score_count', models.IntegerField(default=0, verbose_name='评价人数')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像地址')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
            options={
                'verbose_name': '服务之星',
                'verbose_name_plural': '服务之星',
            },
        ),
        migrations.DeleteModel(
            name='StudentStar',
        ),
        migrations.AlterModelOptions(
            name='auditorprofile',
            options={'verbose_name': '审核员详情', 'verbose_name_plural': '审核员详情'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '订单评论', 'verbose_name_plural': '订单评论'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceprofile',
            options={'verbose_name': '维修员详情', 'verbose_name_plural': '维修员详情'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'verbose_name': '学生详情', 'verbose_name_plural': '学生详情'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': '报修订单', 'verbose_name_plural': '报修订单'},
        ),
        migrations.AlterModelOptions(
            name='ticketattachment',
            options={'verbose_name': '订单附件', 'verbose_name_plural': '订单附件'},
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets_api.ticket', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='评论时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='maintenanceprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('设备故障', '设备故障'), ('水电问题', '水电问题'), ('网络连接', '网络连接'), ('柜子损坏', '柜子损坏'), ('门窗损坏', '门窗损坏'), ('其他', '其他')], max_length=50, verbose_name='报修类别'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='维修地点'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('低', '低'), ('中', '中'), ('高', '高'), ('紧急', '紧急')], max_length=10, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_dorm', '待审核员审核'), ('pending_dispatch', '待派单'), ('repairing', '维修中'), ('finished', '维修完成(待评价)'), ('closed', '已结单'), ('rejected', '已驳回')], default='pending_dorm', max_length=20, verbose_name='报修状态'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='submitTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=200, verbose_name='报修标题'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=tickets_api.models._ticket_media_upload_to, verbose_name='文件内容'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='media_type',
            field=models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=10, verbose_name='媒体类型'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='original_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets_api.ticket', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
    ]
