# Generated by Django 4.2 on 2026-05-17 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0018_adminprofile_delete_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicestar',
            old_name='grade',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='servicestar',
            name='major',
        ),
        migrations.AddField(
            model_name='servicestar',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='所属班组/部门'),
        ),
    ]
