# Generated by Django 4.2 on 2026-05-17 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0019_rename_grade_servicestar_position_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestar',
            name='department',
        ),
        migrations.RemoveField(
            model_name='servicestar',
            name='position',
        ),
    ]
