# Generated by Django 4.2 on 2026-05-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0026_auditorprofile_assigned_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditorprofile',
            name='assigned_worker',
        ),
    ]
