# Generated by Django 4.2 on 2026-05-19 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0028_ticket_repair_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestar',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_star_records', to=settings.AUTH_USER_MODEL, verbose_name='关联维修人员'),
        ),
    ]
