# Generated by Django 4.2 on 2026-05-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0031_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisetting',
            name='llm_enabled',
            field=models.BooleanField(default=False, verbose_name='启用大模型'),
        ),
    ]
