# Generated by Django 4.2 on 2026-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0032_aisetting_llm_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisetting',
            name='api_model_deep',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='深度思考模型'),
        ),
        migrations.AlterField(
            model_name='aisetting',
            name='llm_enabled',
            field=models.BooleanField(default=False, verbose_name='深度思考'),
        ),
    ]
