# Generated by Django 4.2 on 2026-05-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0033_aisetting_api_model_deep_alter_aisetting_llm_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='maintenanceprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='所属部门/工种'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urge_count',
            field=models.IntegerField(default=0, verbose_name='催单次数'),
        ),
    ]
