# Generated by Django 4.2 on 2026-05-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0039_remove_maintenanceprofile_is_online_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='exception_report',
            field=models.TextField(blank=True, default='', verbose_name='异常上报'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='exception_status',
            field=models.CharField(choices=[('无异常', '无异常'), ('异常', '异常')], default='无异常', max_length=10, verbose_name='异常状态'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reimbursement_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='报销单生成时间'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reimbursement_no',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='报销单号'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reimbursement_text',
            field=models.TextField(blank=True, default='', verbose_name='报销单内容'),
        ),
    ]
