# Generated by Django 4.2 on 2025-11-18 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tickets_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='额外区域权限'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='学号/工号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_identity_bound',
            field=models.BooleanField(default=False, verbose_name='是否已绑定身份'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', '学生'), ('teacher', '老师'), ('dorm_manager', '宿管'), ('building_manager', '教学楼管理员'), ('admin', '系统管理员')], default='student', max_length=20, verbose_name='身份角色'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='OARequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_area', models.CharField(max_length=50, verbose_name='申请报修区域')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending_teacher', '待老师审批'), ('pending_admin', '待管理员审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending_teacher', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oa_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
