# Generated by Django 4.2 on 2025-11-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0003_ticket_evaluation_ticket_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('水电设施', '水电设施 (厕所/洗手池/水管/宿舍灯泡)'), ('家具门窗', '家具门窗 (床/柜子/门锁/桌子)'), ('生活电器', '生活电器 (空调/热水器/风扇)'), ('多媒体设备', '多媒体设备 (投影仪/音响/麦克风/电脑)'), ('教学设施', '教学设施 (黑板/桌椅/讲台)'), ('照明设施', '照明/电路'), ('办公设备', '办公设备 (打印机/碎纸机/复印机)'), ('电脑网络', '电脑/网络 (系统/软件/断网)'), ('宿舍设施', '宿舍设施 (走廊灯/走廊饮水机/消防栓/宿舍楼道网络设备)'), ('硬件故障', '硬件故障'), ('软件问题', '软件问题'), ('网络连接', '网络连接'), ('系统权限', '系统权限'), ('其他', '其他')], max_length=50),
        ),
    ]
