# Generated by Django 4.2 on 2026-02-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0006_alter_ticket_description_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '待接单'), (1, '维修中'), (2, '已完成')], default=0, verbose_name='当前状态')),
            ],
        ),
        migrations.CreateModel(
            name='StudentStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业班级')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='年级')),
                ('honor', models.CharField(blank=True, max_length=200, verbose_name='荣誉称号')),
                ('description', models.TextField(blank=True, verbose_name='事迹简介')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像地址')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否展示')),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_dispatch', '正在处理'), ('repairing', '维修中'), ('finished', '维修完成'), ('closed', '已结单'), ('rejected', '已驳回')], default='pending_dispatch', max_length=20),
        ),
    ]
