# Generated by Django 4.2 on 2026-02-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0010_alter_customuser_role_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstar',
            name='score',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='studentstar',
            name='score_count',
            field=models.IntegerField(default=0, verbose_name='评价人数'),
        ),
    ]
