# Generated by Django 4.2 on 2026-02-23 10:44

from django.db import migrations, models
import django.db.models.deletion
import tickets_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0011_studentstar_score_studentstar_score_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='是否匿名评价'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True, verbose_name='驳回理由'),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', '图片'), ('video', '视频')], max_length=10)),
                ('file', models.FileField(upload_to=tickets_api.models._ticket_media_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets_api.ticket')),
            ],
        ),
    ]
