# Generated by Django 4.2 on 2026-05-17 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0015_aisetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('answer', models.TextField(blank=True, default='', verbose_name='AI 回答')),
                ('mode', models.CharField(blank=True, default='', max_length=20, verbose_name='模式')),
                ('ai_enabled', models.BooleanField(default=True, verbose_name='AI 开关状态')),
                ('warning', models.TextField(blank=True, default='', verbose_name='提示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'AI 聊天记录',
                'verbose_name_plural': 'AI 聊天记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
