# Generated by Django 4.2 on 2026-05-17 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0017_servicestar_delete_studentstar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(max_length=50, unique=True, verbose_name='管理员编号')),
                ('permission_level', models.IntegerField(default=1, verbose_name='权限级别')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '管理员详情',
                'verbose_name_plural': '管理员详情',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='auditorprofile',
            name='audited_count',
            field=models.IntegerField(default=0, verbose_name='审核保修单数'),
        ),
        migrations.AddField(
            model_name='maintenanceprofile',
            name='finished_count',
            field=models.IntegerField(default=0, verbose_name='完成维修订单数'),
        ),
        migrations.AddField(
            model_name='maintenanceprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='评分'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='submitted_count',
            field=models.IntegerField(default=0, verbose_name='提交报修单数'),
        ),
    ]
