# Generated by Django 4.2 on 2026-05-17 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0020_remove_servicestar_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='auditor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audited_tickets', to=settings.AUTH_USER_MODEL, verbose_name='审核员'),
        ),
    ]
