# Generated by Django 4.2 on 2026-05-18 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0025_drop_er_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorprofile',
            name='assigned_worker',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_auditor', to=settings.AUTH_USER_MODEL, verbose_name='绑定维修员'),
        ),
    ]
