# Generated by Django 4.2 on 2026-05-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0030_create_thesis_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending_dorm', '待审核员审核'), ('pending_dispatch', '待派单'), ('pending_repair', '待维修'), ('repairing', '维修中'), ('finished', '维修完成(待评价)'), ('closed', '已结单'), ('rejected', '已驳回')], default='pending_dorm', max_length=20, verbose_name='报修状态'),
        ),
    ]
