# Generated by Django 4.2 on 2026-05-22 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0034_maintenanceprofile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='耗材费用'),
        ),
    ]
