# Generated by Django 4.2 on 2026-05-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0035_ticket_material_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceprofile',
            name='is_online',
            field=models.BooleanField(default=True, verbose_name='是否接单(在线)'),
        ),
    ]
