# Generated by Django 4.2 on 2026-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0038_ticket_urge_cd_and_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceprofile',
            name='is_online',
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_auto_approved',
            field=models.BooleanField(default=False, verbose_name='AI自动过审'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_auto_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='AI过审时间'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_auto_reason',
            field=models.TextField(blank=True, default='', verbose_name='AI过审说明'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_suggested_category',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='AI建议类别'),
        ),
    ]
