# Generated by Django 4.2 on 2026-05-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_api', '0040_ticket_exception_report_ticket_exception_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='exception_report',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='exception_status',
        ),
    ]
